#:schema node_modules/wrangler/config-schema.json
name = "poesia-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "TOKENS_KV", id = "3b19b25ca7b54026915360492a674aa4" }
]

[placement]
mode = "smart"


[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1999"
simple = { limit = 30, period = 60 }