name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            XATA_API_KEY
            SUDO_SECRET
        env:
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
          SUDO_SECRET: ${{ secrets.SUDO_SECRET }}