name: Deploy

on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types: 
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            XATA_API_KEY
            SUDO_SECRET
            XATA_DB
        env:
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
          XATA_DB: ${{secrets.XATA_DB}}
          SUDO_SECRET: ${{ secrets.SUDO_SECRET }}